### ISSUE TITLE
No network connectivity?

### ISSUE THREAD

**Issue by Rowdy** [JonathanTreffler/backblaze-personal-wine-container#36] opened 2022-11-25 21:00 UTC
I get this weird error that the container is not able to connect to the internet. Which is weird because I put this container on the same network as all other containers...

https://share.cleanshot.com/JBP8td

`docker run \
    -p 8085:5800 \
    --init \
    --name backblaze_personal_backup_new \
    --network standarddockernetwork \
    -v "/volume1:/drive_d/" \
    -v "/volume1/docker/appdata/backblaze:/config/" \
    -e "TZ=Europe/Berlin" \
    -e "USER_ID=1000" \
    -e "GROUP_ID=1000" \
    tessypowder/backblaze-personal-wine:latest`

**Comment by JonathanTreffler** [comment] 2022-11-26 00:14
duplicate of #4 

The solution is described in the Troubleshooting section of the README (https://github.com/JonathanTreffler/backblaze-personal-wine-container#troubleshooting)

**Closed by JonathanTreffler** 2022-11-26 00:14 UTC
