### ISSUE TITLE
Clients Gets updated even though auto-updated is disabled

### ISSUE THREAD

**Issue by francop311** [JonathanTreffler/backblaze-personal-wine-container#144] opened 2024-04-12 20:23 UTC
I am trying to figure out why my client keeps getting updated to the "pinned" version every 2 hours, so version 9.0.1.767

I enabled the DISABLE_AUTOUPDATE=true flag, and when the container starts up, I see:
 "log_message 'UPDATER: DISABLE_AUTOUPDATE=true, Auto-updates are disabled. Starting Backblaze without updating."

However, after 2 hours, and every 2 hours afterwards, it re-downloads version 9.0.1.767 and installs it.

How do I completely disable re-installation of the client?

**Comment by traktuner** [comment] 2024-04-13 11:05
Hey,
yould you please post the full `backblaze-wine-startapp.log` and the docker logs?

Thank you!

**Comment by francop311** [comment] 2024-04-13 17:01
[backblaze.txt.txt](https://github.com/JonathanTreffler/backblaze-personal-wine-container/files/14968137/backblaze.txt.txt)

Attached is the backblaze-wine-startup.log

There is not much in there. I even blocked web.archive.org from my router to make sure that it does not download the pinned version, but after 4-6 hours, it still finds a way to download the latestest.

**Comment by traktuner** [comment] 2024-04-13 17:08
Thanks for the log! 
I will try to figure out what's wrong there and push a fix.

**Comment by francop311** [comment] 2024-04-13 17:20
What I also noticed is that the latest file appears in the bzupdates folder every 2 hours (after the 2 hour lock file)

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/166869351/e1dde371-4d9e-4e0b-914c-7d169ef7db01)

If  I delete it, it will re-appear again...

**Comment by traktuner** [comment] 2024-04-13 17:41
Those 2 files are not files created by our container - those are files downloaded by the Backblaze app itself. I need to check if they are currently forcing updates to a speific version.
`DISABLE_AUTOUPDATE=true` can only disable our own update function but not when Backblaze forces an update from their side.

**Comment by francop311** [comment] 2024-04-13 17:48
I see.. However, I have the DISABLE_AUTOUPDATE=true flag, yet it still updates to the latest version (after a few hours). I thought it was pulling this client from web.archive.org, which is why I even blocked this URL on my router.

Anyways, if you can look into this, that would be great.

Thanks

**Comment by francop311** [comment] 2024-04-13 19:02
Just to let you know, it re-updated it's self to the latest version again. If I know where the backblaze client downloads the file, then I can possibly block it from my router...

**Comment by francop311** [comment] 2024-04-14 01:25
I think I figured out how to block updates from backblaze. If you block this domain on you router:
f000.backblazeb2.com

It will not be able to download the client.

So for, (over 8 hours) and the bzupdate folder is empty. The only think that gets updated in the folder is the lck file:

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/166869351/749d5c29-b4b4-442a-b41e-0e00503c2fc5)

Wish there was another way to prevent updates.....

**Comment by j-peeters** [comment] 2024-04-14 16:46
@francop311, I was happy to see this thread and your suggestion because I have the same problem. But when I block the domain, uninstall the 9.0.1.767 version, upload the 9.0.0.749 and install it. BZ still succeeds to updating itself to the latest 9.0.1.767.

My bzupdates folders are empty, apart from a clientversion.xml file. No bzautoupdates lck files to be found. 
It almost seems as if it can update in-app because in the Backblaze appdata folder I cannot find any newly downloaded installers and the one I uploaded myself is still at version 9.0.0.749 (when I redownload it and check it). 
It could also be that BackBlaze has multiple DL locations but that still doesn't clarify how it updates itself.

It's a mysterious case. Any ideas are welcome.

**Comment by traktuner** [comment] 2024-04-14 16:55
Backblaze has indeed an in-app autoupdate function but they rarely force updates. Only when there is a nasty bug which affects a larger userbase.
I will try to find out what's happening here and let you guys know.

**Comment by j-peeters** [comment] 2024-04-14 17:04
Thanks @traktuner

The reason I would like to try downgrading is because I'm trying to get past incredibly slow uploads, as reported in threads #59 and #130 (0.7 mbps). 
I tried many things like :ubuntu22 tags, deselect throttling, reinstalling etc. 
I'm on a decent 200 Mbps symmetrical fiber channel network on a rather fast Intel NUC so that should do I'd say.

But if they only push an update this in case of nasty bugs, it might not be wise to downgrade. 
Do you experience any of these issues as reported in #130 and #59?

**Comment by francop311** [comment] 2024-04-14 17:22
Yes, that is the reason as well for me. I have about 6 TB to transfer and with version 9.0.1.767, it was uploading at about 6-7Mbs, where if I use 9.0.0.749, it transfers at over 400Mbs.

@j-peeters regarding your bzupdates folder, it is weird that you have the clientversion.xml file. I don't get this.

Are you blocking both the following domains:
- web.archive.org
- f000.backblazeb2.com
It is possible that it is actually using the "pinned" version and not the backblaze auto-update version.

Thanks

**Comment by traktuner** [comment] 2024-04-14 17:42
@j-peeters 
I am on the latest Backblaze version and my upload speed saturates my connection (100Mbit)
Are you using unraid?
I have a Synology setup. I tried to debug the speed issue but as far as I can tell it's not related to our Docker container but a Backblaze app thing.

**Comment by newoski** [comment] 2024-04-14 17:44
(I started this issue thread and — to offer a bit of hope — I’ve been
seeing about 150mbit up for a few weeks)

**Comment by j-peeters** [comment] 2024-04-14 17:49
I'm indeed on Unraid. At first, I thought they may have discovered a way to detect that files are being uploaded from a server, but a Synology is also Linux-based, I guess? So that would be the same thing. It's interesting that you have no problems on Synology, but Unraid users have.

I'll give it a last try and thereafter, I'll accept that it will take 2 months to UL everything. Subsequently, it's trickle UL anyway when the bulk is safe. Thanks so far!

**Comment by newoski** [comment] 2024-04-14 17:51
(I’m also on Unraid. 150mbit up on a 350mbit connection)

**Comment by traktuner** [comment] 2024-04-14 17:54
> (I’m also on Unraid. 150mbit up on a 350mbit connection)

I know, but it seems this is still an Unraid issue.
We all use the same Docker image which is an Ubuntu distro and only Unraid users report those speed issues.
Would be interesting if there are also reports regarding docker speed issues in dedicated Unraid forums ... Maybe there's a bug with Unraid docker networking...

**Comment by j-peeters** [comment] 2024-04-14 18:10
I just succeeded (for a few minutes) in using the 9.0.0.749 version and the speeds were like they should. But after two minutes, BB closed itself and subsequently, it restarted with version 9.0.1.767. Speeds are slow again. 
It could have something to do with Unraid but since the previous version works fine and the newer version not, I have no idea what that could be.

**Comment by j-peeters** [comment] 2024-04-14 18:22
@traktuner maybe you or a colleague maintainer can find a way to lock down the BB autoupdate system (making relevant folders read only with a docker setting or so) so that we can stay in version 9.0.0.749 for a bit until someone confirms that a newer version works as it should.

**Comment by traktuner** [comment] 2024-04-14 18:25
@j-peeters 
I will definetely look into it. But it sill take some time - currently lots of other things to do..

**Comment by j-peeters** [comment] 2024-04-14 18:27
No problem @traktuner, I'm grateful that you're willing to look into this.

**Comment by francop311** [comment] 2024-04-14 22:21
Thank you again @j-peeters  and @traktuner for looking into this.

The quickest way, maybe, is to create a new "flag" for the installer, something like PREVENT_BZUPDATE and in the startup script create an entry in the host file to point to 127.0.0.1 for f000.backblazeb2.com.

Just an idea.

Thanks again for all your work. Really love this project and is a life-saver...

**Comment by francop311** [comment] 2024-04-15 04:32
> > (I’m also on Unraid. 150mbit up on a 350mbit connection)
> 
> I know, but it seems this is still an Unraid issue. We all use the same Docker image which is an Ubuntu distro and only Unraid users report those speed issues. Would be interesting if there are also reports regarding docker speed issues in dedicated Unraid forums ... Maybe there's a bug with Unraid docker networking...

Just for clarity, I am NOT on Unraid, I'm actually using Openmediavault and have the same issue. Maybe it has something to do with the linux distro?

**Comment by traktuner** [comment] 2024-04-15 04:39
> Just for clarity, I am NOT on Unraid, I'm actually using Openmediavault and have the same issue. Maybe it has something to do with the linux distro?

No, probably some underlying config on the host system.
I am using Synology and have no issues with ubuntu20 or ubuntu22.

> The quickest way, maybe, is to create a new "flag" for the installer, something like PREVENT_BZUPDATE and in the startup script create an entry in the host file to point to 127.0.0.1 for f000.backblazeb2.com.

We already have the DISABLE_AUTOUPDATE flag. I will try to enhance this feature in the coming weeks that this does more things than just "not" running out own updater.

**Comment by francop311** [comment] 2024-04-15 04:42
> > Just for clarity, I am NOT on Unraid, I'm actually using Openmediavault and have the same issue. Maybe it has something to do with the linux distro?
> 
> No, probably some underlying config on the host system. I am using Synology and have no issues with ubuntu20 or ubuntu22.
> 
> > The quickest way, maybe, is to create a new "flag" for the installer, something like PREVENT_BZUPDATE and in the startup script create an entry in the host file to point to 127.0.0.1 for f000.backblazeb2.com.
> 
> We already have the DISABLE_AUTOUPDATE flag. I will try to enhance this feature in the coming weeks that this does more things than just "not" running our own updater.

I really appreciate it.

**Comment by j-peeters** [comment] 2024-04-15 04:43
Just wanted to add that the suggestion of @francop311  might not work for all. I have blocked both sites on my router and it still succeeds in updating.

**Comment by traktuner** [comment] 2024-04-15 04:44
> Just wanted to add that the suggestion of @francop311 might not work for all. I have blocked both sites on my router and it still succeeds in updating.

There are many more URLs ;)

**Comment by j-peeters** [comment] 2024-04-15 05:32
I figured ;-)

**Comment by francop311** [comment] 2024-04-15 20:52
> > Just wanted to add that the suggestion of @francop311 might not work for all. I have blocked both sites on my router and it still succeeds in updating.
> 
> There are many more URLs ;)

True. I just had to go through my DNS logs and see and compare the timestamp of when the the lck file gets updated with the actual DNS entry. I then noticed the same entry would appear at exactly the same time every 2 hours. For me, it was f000.backblazeb2.com. 

There are other hosts, but it would depend where you are located and which one is closes to your location. However, a quick search pointed me to the following list: 
api.backblazeb2.com
f002.backblazeb2.com
api002.backblazeb2.com
f003.backblazeb2.com
api003.backblazeb2.com
f001.backblazeb2.com
f005.backblazeb2.com
zenoimages.s3.us-west-001.backblazeb2.com
blocksi-screenshots-us.s3.us-east-005.backblazeb2.com
api001.backblazeb2.com
api000.backblazeb2.com
f000.backblazeb2.com
api004.backblazeb2.com
dam-novastream.s3.us-west-002.backblazeb2.com
f004.backblazeb2.com
s3.us-west-004.backblazeb2.com
planweb-nuvemshop.s3.us-west-004.backblazeb2.com
beaware-mastodon.s3.us-east-005.backblazeb2.com

I am not saying that we should block all of them, but it is worth looking into. :-)

For me, If you want to temporary stop the client from downloading the updated client, it was f000.backblazeb2.com.

**Comment by tirthpatell** [comment] 2024-04-16 02:58
Seeing the same problem for the last couple of weeks. Upload speed is stuck at 6-9 Mbps, I used to saturate my 300Mbps upload speed. I am also on unraid FYI. It does not matter how many threads I assign; it never exceeds 9Mbps. I have 96GB RAM in total; there is no issue on that side.

![CleanShot 2024-04-15 at 21 54 43@2x](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/32465104/647ccec1-cacd-431a-b25e-48f7a9a0578f)

**Comment by traktuner** [comment] 2024-04-16 06:23
According to my investigations the only URL where official auto-updates are downloaded from is f000.backblazeb2.com which will be blocked by setting `DISABLE_AUTOUPDATE=true` when #145 is merged.

To note: It's not necessary to block web.archive.org since this is only used for our own updater which is also completely disabled when using the above environment variable.
Hope that helps!

**Comment by j-peeters** [comment] 2024-04-16 10:11
Thanks for looking into this @traktuner. I'm not sure whether this is the whole fix, though. 
I have blocked f000.backblazeb2.com on the router level and just uninstalled BackBlaze from my Wine. I ULed a new 9.0.0.749 to wine and installed it. Still BackBlaze succeeded to update itself (even during the installation) to 9.0.1.767. 

There was an update this morning to the BackBlaze docker and I installed that. I hope your fix is not yet pulled into that one so that there is still a chance that when it has been pulled in, the blocking works.
Maybe I'm just doing something wrong, but if not, there might be another update route for BB. I'm in the EU, maybe that makes a difference.

**Comment by traktuner** [comment] 2024-04-16 10:21
> Thanks for looking into this @traktuner. I'm not sure whether this is the whole fix, though. I have blocked f000.backblazeb2.com on the router level and just uninstalled BackBlaze from my Wine. I ULed a new 9.0.0.749 to wine and installed it. Still BackBlaze succeeded to update itself (even during the installation) to 9.0.1.767.
> 
> There was an update this morning to the BackBlaze docker and I installed that. I hope your fix is not yet pulled into that one so that there is still a chance that when it has been pulled in, the blocking works. Maybe I'm just doing something wrong, but if not, there might be another update route for BB. I'm in the EU, maybe that makes a difference.

In my testing, also in the EU, f000 is the only location I could find.
I can't block any other locations other than those b2 buckets because that would also block the "real" backup traffic.
The pull request is not yet merged, so there is still hope.
If there is no backblaze installation present at all and you start the container it automatically downloads the pinned known-good version which is currently 9.0.2.767
If you coult somehow trace exaclty which URL it's pulling the installer from, that would definetely help.

**Comment by j-peeters** [comment] 2024-04-16 10:47
Hi @traktuner thanks a lot for your speedy responses, it makes this process a lot more fluent.

I looked at my startup log and found the following:

`Tue Apr 16 10:29:48 AM Etc 2024: WINE: Enabling Virtual Desktop mode with 900:900 aspect ratio
Tue Apr 16 10:29:54 AM Etc 2024: INSTALLER: FORCE_LATEST_UPDATE=false - downloading pinned version 9.0.1.767 from archive.org
Tue Apr 16 10:30:05 AM Etc 2024: INSTALLER: Starting install_backblaze.exe
Tue Apr 16 10:34:47 AM Etc 2024: STARTAPP: Starting Backblaze version 9.0.1.767`

So, as you already wrote, that makes it go to the latest pinned version. 
What I don't understand though is that when after uninstall the newest version, I place a 9.0.0.749 version in the root of the drive_c with the name 'install_backblaze.exe' 

In my docker settings I have also set 
DISABLE_AUTOUPDATE: true

Maybe I'm missing something.

**Comment by traktuner** [comment] 2024-04-16 10:49
Then the app behaves as it should. It does not matter if there is an install_backblaze file. It checks if Backblaze really is installed, not if the installer is present.
You would manually (via docker command line) install the version you need.

**Comment by j-peeters** [comment] 2024-04-16 11:03
Ah, okay. So I missed that crucial part. 
Meanwhile, I've been able to install the 9.0.0 version via wine explorer by also temporarily blocking the archive.org URL. It's now installed at version 9.0.0 and scanning my disks. So I'm hopeful it'll hold. When your fix is merged I'll remove the block and see if the 9.0.0 version will stick. 

Would you mind telling me what command I type in the docker command line to install the 9.0.0 version? I'm not too well versed in docker, so I'd like to learn. And would be useful for another time. Thanks.

**Comment by traktuner** [comment] 2024-04-16 11:21
> Would you mind telling me what command I type in the docker command line to install the 9.0.0 version? I'm not too well versed in docker, so I'd like to learn. And would be useful for another time. Thanks.

Sure!
Make sure the setup file is called install_backblaze.exe and located in the root direcotry of wine (your config folder - wine - drive_c)
When the docker container is running, start the docker shell
`docker exec -it backblaze-personal-wien /bin/bash`
and then
`cd /config/wine/dosdevices/c:/` (to get into the installer directory)
`wine64 "install_backblaze.exe"` (start the installer)
Then you should see the Backblaze installer window.

**Closed** 2024-04-16 12:23 UTC

**Comment by j-peeters** [comment] 2024-04-16 12:30
That's for the explanation. I saw the fix was merged. I hope that another user can confirm that it indeed doesn't auto update anymore? Then I can remove the router blocks. Thanks @traktuner

**Comment by francop311** [comment] 2024-04-16 13:30
> Thanks for the explanation. I saw the fix was merged. I hope that another user can confirm that it indeed doesn't auto update anymore? Then I can remove the router blocks. Thanks @traktuner
> 
> By the way, I had my installer named like you said but the auto installer didn't pick it up. Maybe a permissions issue. But it works now!

Excellent. Thanks @traktuner for the quick turn around. I thought I was the only one with the issue, glad this could help others. :-)

**Comment by francop311** [comment] 2024-04-16 13:33
> According to my investigations the only URL where official auto-updates are downloaded from is f000.backblazeb2.com which will be blocked by setting `DISABLE_AUTOUPDATE=true` when #145 is merged.
> 
> To note: It's not necessary to block web.archive.org since this is only used for our own updater which is also completely disabled when using the above environment variable. Hope that helps!

Perfect. That is what I found as well and one other reason why I had blocked only f000.backblazeb2.com.  Great that this was an easy fix ;-)

**Comment by traktuner** [comment] 2024-04-16 14:16
> easy fix

Actually it was not "that" easy. I had to walk through all URLs separately with all known paths if there is a downloadable setup there. We don't rush things here ;)

**Comment by francop311** [comment] 2024-04-16 20:23
BTW. For me the update did not work. 

It seems that the entry for f000.backblazeb2.com in the /etc/hosts is not being populated, as I get a "permissions denied" when startup.sh script is trying to update the hosts file.

**Comment by traktuner** [comment] 2024-04-17 03:15
Hey,
thanks, I will check that. 
For me it works, downloading the installer via cURL from that URL does not work within the container.

**Comment by traktuner** [comment] 2024-04-17 05:05
> BTW. For me the update did not work.
> 
> It seems that the entry for f000.backblazeb2.com in the /etc/hosts is not being populated, as I get a "permissions denied" when startup.sh script is trying to update the hosts file.

Please try to add this to your docker run command:
`--add-host=f000.backblazeb2.com:127.0.0.1`

**Comment by j-peeters** [comment] 2024-04-17 18:15
Hi @traktuner It's unclear to me how to add something to a docker run command in Unraid since Unraid works with a page of settings like this:

![20240417 docker settings](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/4502360/019eaca0-f7ea-4f0c-999f-260573f09bb7)

And afterward you 'just' start the container via a dropdown menu.
Maybe someone knows how to do this?

**Comment by j-peeters** [comment] 2024-04-17 18:25
Thanks! Would that be like so?

![20240417 Docker block host](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/4502360/b457465b-1420-4b46-bf38-da23f0ef6082)

it ends up being like this:

![20240417 Docker Block BB2](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/4502360/1c151d32-291b-4662-98b4-979495690538)

Or do the -- before host also need to be added?

**Comment by JonathanTreffler** [comment] 2024-04-17 18:32
Variable is wrong. You need to activate advanced mode and paste it into a field, I don't remember what label that field has, if you send a screenshot with advanced mode activated I can say which

**Comment by j-peeters** [comment] 2024-04-17 18:37
Thanks for all the endured help! This is the advanced view, anyway the part that differs from the basic view. 

![20240417 Docker Advanced 2](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/4502360/349fd4e6-5b5c-4e50-b9c0-f34757f2063d)

**Comment by JonathanTreffler** [comment] 2024-04-17 18:38
You need to paste " --add-host=f000.backblazeb2.com:127.0.0.1" into "Extra Parameters". Make sure there is a space in between "--init" and the new parameter.

**Comment by j-peeters** [comment] 2024-04-17 18:39
Terrific, thanks @JonathanTreffler and @traktuner!

**Comment by j-peeters** [comment] 2024-04-17 18:43
Sorry last question, where would I find the hosts file on the server to check if the line is properly added?

**Comment by JonathanTreffler** [comment] 2024-04-17 18:46
I think --add-host works works without it adding anything to the hosts file, but if it does, that would be /etc/hosts *whithin* the docker container. This is not accessible outside the container, you need to open a shell in the container (possible in the Unraid Docker GUI), not a general system shell.

**Comment by francop311** [comment] 2024-04-17 18:50
> I think --add-host works works without it adding anything to the hosts file, but if it does, that would be /etc/hosts _whithin_ the docker container. This is not accessible outside the container, you need to open a shell in the container (possible in the Unraid Docker GUI), not a general system shell.

For me, I'm using portainer and use compose files to run each container. However, if we have to manually add the entries in the host file, then we can get rid of the "DISABLE_AUTOUPDATE=true" flag?

For me, blocking at router level works easiest for me.

**Comment by j-peeters** [comment] 2024-04-17 18:52
Thanks, I checked the hosts file with vi in the docker, and the line is not in there. 
So I guess it works in another way. 
For now, I'll also stick with the blocking at the router level. If someone has confirmed that a newer BB version solves the slow uploads I'll remove them. 
But I think this thread now gives good info for other Unraid users trying to troubleshoot this. So thanks again!

**Comment by francop311** [comment] 2024-04-17 19:00
> Thanks, I checked the hosts file with vi in the docker, and the line is not in there. When I check how the '--ad-host' should work with Kagi search it states:
> 
> > The --add-host option in the docker run command allows you to add custom host-to-IP mappings to the container's /etc/hosts file.
> 
> Maybe caused by the permissions issue that @francop311 reported earlier. For now, I'll also stick with the blocking at the router level. If someone has confirmed that a newer BB version solves the slow uploads I'll remove them. But I think this thread now gives good info for other Unraid users trying to troubleshoot this. So thanks again!

Same here.

Just for completeness, this is the last lines of my log:

```
[app         ] Auto-updates are disabled. Backblaze won't be updated.
[app         ] + '[' -f '/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe' ']'
[app         ] + '[' true = true ']'
[app         ] + echo '127.0.0.1    f000.backblazeb2.com'
[app         ] /startapp.sh: line 127: /etc/hosts: Permission denied
[app         ] + log_message 'UPDATER: DISABLE_AUTOUPDATE=true, Auto-updates are disabled. Starting Backblaze without updating.'
```

**Comment by rursache** [comment] 2024-09-05 21:10
blocking `f000.backblazeb2.com` in hosts in not enough, the update will be downloaded anyway.

the solution is to create a empty FILE named `bzupdate` and `bzupdates`

**Comment by j-peeters** [comment] 2024-10-30 09:29
> blocking `f000.backblazeb2.com` in hosts in not enough, the update will be downloaded anyway.
> the solution is to create a empty FILE named `bzupdate` and `bzupdates`

For me blocking:
`f000.backblazeb2.com`
`archive.org`
for the respective server on the router level has worked fine. I'm still at the old version that runs fast.
